### PR TITLE
Updated build.gradle (app)

### PR DESCRIPTION
**Pull request by J-KC-Man**
Updated to latest version of SDK and Build tools:

 compileSdkVersion 27
 buildToolsVersion '27.0.1'
 targetSdkVersion 27

from pre-release strings to fix issues of missing platform-tools and syncing Gradle files for initial code.

### CODE REVIEW

**Comment by J-KC-Man** [comment]
I signed it!

**Comment by adriantache** [comment]
Good job making this pull request, I wasted about 15 minutes fixing it myself today. I can't imagine why it's taking Google almost a year to accept it :/

**Comment by J-KC-Man** [comment]
Thanks, yes that's unfortunate. Can't believe it hasn't been accepted yet! Glad to help others out in the meantime.

**Comment by adriantache** [comment]
I guess if even their documentation code is outdated, these code samples on github are even lower priority than that.

**Pull request closed without merging**
